### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by mwolny**

### CODE REVIEW

**Comment by vesche** [comment]
Sorry for the late reply on this. I don't think this is something that needs to be included with this repo. Thanks for the interest.

**Comment by vesche** [comment]
I'm not against it. I just think that this tool isn't something you would typically run inside of a container. Doesn't hurt anything to merge this I suppose. Does the Dockerfile made by @kqqkqq look good to you @AmauryOrtega ?

**Comment by AmauryOrtega** [comment]
It's fine but I would make a few editions:

- Running the command as non-root user
- Using a smaller footprint like alpine as a base image
- Installing `scanless` using pip so it gets the last version

It's also possible to use a web hook from github to docker hub so that at each new tag you make, docker hub fetches the `Dockerfile` and builds a new image with the corresponding tag under your username like `vesche/scanless:$TAG`. Let me know if you're interested in this functionality. I've made a pull request with my version of the `Dockerfile` and an uptaded `README.md`. #15

**Comment by drwetter** [comment]
yeah, please no root inside the container and alpine linux which has not a shitload of not needed binaries on board.

**Pull request closed without merging**
